# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nicolás Miari
#email: nicolasmiari@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Java is what you drink and Cocoa is what you code, and <strong>not</strong> the other way around.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nicolasmiari.com" # the base hostname & protocol for your site
twitter_username: nicolasmiari
github_username:  nicolas-miari

# Build settings
markdown: kramdown
include: ['_pages', '_pages/apps/spotlighter', '_pages/apps/icon-set-creator']
